num1 = input("Enter your first number:")
num2 = input("Enter your second number:")
sum = float(num1) + float(num2)
sub = float(num1) - float(num2)
mul = float(num1) * float(num2)
div = float(num1) / float(num2)
print("Sum is {} ".format(sum))
print("Subtract is {} ".format(sub))
print("Multiply is {} ".format(mul))
print("Division is {} ".format(div))